### ISSUE TITLE
Not working with Firefox 37? (moz- prefix?)

### ISSUE THREAD

**Issue by mautematico** [hadimichael/gest.js#2]
I was trying to play 2048 Air with no success. Then I tried all of the demos: no one worked.

this one: http://stoptheelves.thirststudios.com/ is requesting me to download a webkit browser.
But I think we can make gests.js work with Firefox Release and even Firefox for Android and Firefox OS:
http://caniuse.com/#search=getUserMedia

**Comment by mautematico** [comment]
Hmmm maybe the demos are all just out-of-date with v0.5
"Firefox support (woohoo!)"

:)

**Comment by hadimichael** [comment]
Yeah, many of the demos were built before v0.5 - it took me a while to get Firefox support into the lib.

The SlidesJS demo works in FF: http://hadi.io/gest.js/demos/slidesjs/index.html
